name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build resume
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: LaTeX linter
      uses: j2kun/chktex-action@v1.0.2
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: resume.tex
      #    - name: Build
#      run: make build
