name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build resume
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

#    - name: Build
#      run: make build
